### PR TITLE
Change to using time interval as the coord name

### PR DESCRIPTION
**Pull request by arm61**
@Harry-Rich could you give me your thoughts on this PR? Check, in particular that the name "time interval" matches your understanding of the axis.

### CODE REVIEW

**Review by Harry-Rich — COMMENTED** [review]
I have talked it over with Josh and think it is a good change as we're not talking about the timestep, we're talking about an average over all of the time windows for each step so time interval makes sense to me. 

As a slight aside

When you define the covariance matrix is there a way to have the dimensions have the same name, because they're not really 2 separate dimensions are they? It's the correlation of the time interval with itself as a 2D array. 

Screenshot 2024-09-24 at 13 30 10

**Comment by arm61** [comment]
> When you define the covariance matrix is there a way to have the dimensions have the same name, because they're not really 2 separate dimensions are they? It's the correlation of the time interval with itself as a 2D array.

I don't think so cause the dimensions need unique labels. I guess we can ask on the scipp issue tracker though.

**Comment by bjmorgan** [comment]
They are different time indices. Any object correlated with itself == 1.

**Comment by arm61** [comment]
I am thinking about it more, they are *I think* different "dimensions" in the array sense, if not the physical sense.

**Comment by arm61** [comment]
I think that in a physical sense, the dimensions are the same, i.e., the coordinate is time interval on both. This is true for all covariance matrices. As @jl-wynen (one of the scipp developers) put it:
> a matrix may have two ranks that exist in the same dimension.

**Pull request merged**
