### PR TITLE
hdf extension handling

### PR DESCRIPTION
**Pull request by alexsquires**
My proposed solution to #33

### CODE REVIEW

**Comment by alexsquires** [comment]
It works, because the split(".") returns the whole string in a single element list.  

```
In [5]: "my_file".split(".")
Out[5]: ['my_file']

In [6]: "my_file".split(".")[0] + ".hdf"
Out[6]: 'my_file.hdf'
```

**Comment by arm61** [comment]
Ahh even if there is no full stop! Nice one. 

I don’t think this functionality is covered by tests at all yet. Could you add them and we can bump the 91% coverage up a bit?

**Comment by alexsquires** [comment]
Oops. Missing a CI dependancy again

**Comment by arm61** [comment]
Looks good to me! Let’s merge.

**Pull request merged**
